helpdesk/urls.py
"""
django-helpdesk - A Django powered ticket tracker for small enterprise.

(c) Copyright 2008 Jutda. All Rights Reserved. See LICENSE for details.

urls.py - Mapping of URL's to our various views. Note we always used NAMED
          views for simplicity in linking later on.
"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from helpdesk.decorators import helpdesk_staff_member_required, protect_view
from helpdesk import settings as helpdesk_settings
from helpdesk.views import feeds, staff, public, kb, login
try:
    # TODO: why is it imported? due to some side-effect or by mistake?
    import helpdesk.tasks  # NOQA
except ImportError:
    pass


class DirectTemplateView(TemplateView):
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        if self.extra_context is not None:
            for key, value in self.extra_context.items():
                if callable(value):
                    context[key] = value()
                else:
                    context[key] = value
        return context


app_name = 'helpdesk'

base64_pattern = r'(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'

urlpatterns = [
    url(r'^dashboard/$',
        staff.dashboard,
        name='dashboard'),

    url(r'^tickets/$',
        staff.ticket_list,
        name='list'),

    url(r'^tickets/tags/$',
        staff.get_tags,
        name='get_tags'),

    url(r'^tickets/update/$',
        staff.mass_update,
        name='mass_update'),

    url(r'^tickets/update_tags/$',
        staff.mass_update_tags,
        name='mass_update_tags'),
    
    url(r'^tickets/get_elapsed_time/(?P<ticket_id>[0-9]+)/$',
        staff.get_elapsed_time,
        name='get_elapsed_time'),

    
    url(r'^tickets/start_timer/$',
        staff.start_timer,
        name='start_timer'),
    
    url(r'^tickets/stop_timer/$',
        staff.stop_timer,
        name='stop_timer'),


    url(r'^tickets/merge$',
        staff.merge_tickets,
        name='merge_tickets'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/$',
        staff.view_ticket,
        name='view'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/followup_edit/(?P<followup_id>[0-9]+)/$',
        staff.followup_edit,
        name='followup_edit'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/followup_delete/(?P<followup_id>[0-9]+)/$',
        staff.followup_delete,
        name='followup_delete'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/edit/$',
        staff.edit_ticket,
        name='edit'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/update/$',
        staff.update_ticket,
        name='update'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/delete/$',
        staff.delete_ticket,
        name='delete'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/hold/$',
        staff.hold_ticket,
        name='hold'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/unhold/$',
        staff.unhold_ticket,
        name='unhold'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/$',
        staff.ticket_cc,
        name='ticket_cc'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/add/$',
        staff.ticket_cc_add,
        name='ticket_cc_add'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/delete/(?P<cc_id>[0-9]+)/$',
        staff.ticket_cc_del,
        name='ticket_cc_del'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/dependency/add/$',
        staff.ticket_dependency_add,
        name='ticket_dependency_add'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/dependency/delete/(?P<dependency_id>[0-9]+)/$',
        staff.ticket_dependency_del,
        name='ticket_dependency_del'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/attachment_delete/(?P<attachment_id>[0-9]+)/$',
        staff.attachment_del,
        name='attachment_del'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/beam_unpair/(?P<inventory_type>(property|taxlot))/(?P<inventory_id>[0-9]+)/$',
        staff.beam_unpair,
        name='ticket_beam_unpair'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/edit_tags/$', staff.edit_ticket_tags, name='edit_ticket_tags'),

    url(r'^raw/(?P<type>\w+)/$',
        staff.raw_details,
        name='raw'),

    url(r'^rss/$',
        staff.rss_list,
        name='rss_index'),

    url(r'^reports/$',
        staff.report_index,
        name='report_index'),

    url(r'^reports/(?P<report>\w+)/$',
        staff.run_report,
        name='run_report'),

    url(r'^save_query/$',
        staff.save_query,
        name='savequery'),

    url(r'^delete_query/(?P<id>[0-9]+)/$',
        staff.delete_saved_query,
        name='delete_query'),

    url(r'^reject_query/(?P<id>[0-9]+)/$',
        staff.reject_saved_query,
        name='reject_query'),

    url(r'^reshare_query/(?P<id>[0-9]+)/$',
        staff.reshare_saved_query,
        name='reshare_query'),

    url(r'^unshare_query/(?P<id>[0-9]+)/$',
        staff.unshare_saved_query,
        name='unshare_query'),

    url(r'^settings/$',
        staff.EditUserSettingsView.as_view(),
        name='user_settings'),

    url(r'^ignore/$', staff.email_ignore, name='email_ignore'),
    url(r'^ignore/add/$', staff.email_ignore_add, name='email_ignore_add'),
    url(r'^ignore/edit/(?P<id>[0-9]+)/$', staff.email_ignore_edit, name='email_ignore_edit'),
    url(r'^ignore/delete/(?P<id>[0-9]+)/$', staff.email_ignore_del, name='email_ignore_del'),

    url(r'^tag/$', staff.tag_list, name='tag_list'),
    url(r'^tag/add/$', staff.tag_add, name='tag_add'),
    url(r'^tag/edit/(?P<id>[0-9]+)/$', staff.tag_edit, name='tag_edit'),
    url(r'^tag/delete/(?P<id>[0-9]+)/$', staff.tag_delete, name='tag_delete'),

    url(r'^preset_reply/$', staff.preset_reply_list, name='preset_reply_list'),
    url(r'^preset_reply/add/$', staff.preset_reply_add, name='preset_reply_add'),
    url(r'^preset_reply/edit/(?P<id>[0-9]+)/$', staff.preset_reply_edit, name='preset_reply_edit'),
    url(r'^preset_reply/delete/(?P<id>[0-9]+)/$', staff.preset_reply_delete, name='preset_reply_delete'),

    url(r'^email_template/$', staff.email_template_list, name='email_template_list'),
    url(r'^email_template/edit/(?P<id>[0-9]+)/$', staff.email_template_edit, name='email_template_edit'),
    url(r'^email_template/default/(?P<id>[0-9]+)/$', staff.email_template_default, name='email_template_default'),

    url(r'^payment/settings/$', staff.payment_settings,  name='payment_settings'),

    url(r'^preview_html$', staff.preview_html, name="preview_html"),

    url(r'^timeline_ticket_list/(?P<query>{})$'.format(base64_pattern),
        staff.timeline_ticket_list,
        name="timeline_ticket_list"),

    url(r'set_default_org/(?P<user_id>[0-9]+)/(?P<org_id>[0-9]+)/$',
        staff.set_default_org,
        name="set_default_org"),

    url(r'set_user_timezone/$',
        staff.set_user_timezone,
        name="set_user_timezone"),

    url(r'emails/(?P<ticket_id>[0-9]+)/$',
        staff.enable_disable_emails,
        name="enable_disable_emails"),

    url(r'pair_property_milestone/(?P<ticket_id>[0-9]+)/$',
        staff.pair_property_milestone,
        name="pair_property_milestone"),

    url(r'pair_property_ticket/(?P<ticket_id>[0-9]+)/$',
        staff.pair_property_ticket,
        name="pair_property_ticket"),

    url(r'copy_to_beam/(?P<ticket_id>[0-9]+)/$',
        staff.load_copy_to_beam,
        name="copy_to_beam"),

    url(r'get_building_data/(?P<ticket_id>[0-9]+)/$',
        staff.get_building_data,
        name="get_building_data"),

    url(r'update_building_data/(?P<ticket_id>[0-9]+)/$',
        staff.update_building_data,
        name="update_building_data"),

    url(r'edit_inventory_labels/(?P<inventory_type>(property|taxlot))/(?P<ticket_id>[0-9]+)/$',
        staff.edit_inventory_labels,
        name="edit_inventory_labels"),

    url(r'export_report/$',
        staff.export_report,
        name="export_report"),
]

urlpatterns += [
    # 9/24: Removed form and 'View Ticket' feature from homepage -- so just display the KB home. Add this back later
    # url(r'^$',
    #    protect_view(public.Homepage.as_view()),
    #    name='home'),

    url(r'^tickets/submit/(?P<form_id>[0-9]+)/$',
        public.create_ticket,
        name='submit'),

    url(r'^tickets/submit_iframe/$',
        public.CreateTicketIframeView.as_view(),
        name='submit_iframe'),

    url(r'^tickets/success_iframe/$',  # Ticket was submitted successfully
        public.SuccessIframeView.as_view(),
        name='success_iframe'),

    url(r'^view/$',
        public.view_ticket,
        name='public_view'),

    url(r'^evaluate_derived_column/$',
        public.evaluate_derived_column,
        name='evaluate_derived_column'),

    url(r'^change_language/$',
        public.change_language,
        name='public_change_language'),
    
    url(r'^bps_pathway_calculator/$',
        public.bps_pathway_calculator,
        name='public_bps_pathway_calculator'),

    url(r'^payment/$',
        public.BuildingOrderView.as_view(),
        name='payment'),

    url(r'^payment/property/$',
        public.lookup_building_for_payment,
        name='lookup_building_for_payment'),

    url(r'^payment/complete/$', public.payment_complete, name='payment_complete'),
    url(r'^payment/canceled/$', public.payment_failed, name='payment_canceled'),
    url(r'^payment/failed/$', public.payment_failed, name='payment_failed'),
    url(r'^payment/duplicate/$', public.payment_failed, name='payment_duplicate'),
]

urlpatterns += [
    url(r'^rss/user/(?P<user_name>[^/]+)/$',
        helpdesk_staff_member_required(feeds.OpenTicketsByUser()),
        name='rss_user'),

    url(r'^rss/user/(?P<user_name>[^/]+)/(?P<queue_slug>[A-Za-z0-9_-]+)/$',
        helpdesk_staff_member_required(feeds.OpenTicketsByUser()),
        name='rss_user_queue'),

    url(r'^rss/queue/(?P<queue_slug>[A-Za-z0-9_-]+)/$',

helpdesk/templates/helpdesk/edit_ticket.html
{% extends "helpdesk/base.html" %}

{% load i18n bootstrap4form %}

{% block helpdesk_title %}{% trans "Edit Ticket" %}{% endblock %}

{% block helpdesk_breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'helpdesk:list' %}">{% trans "Tickets" %}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'helpdesk:list' %}{{ ticket.id }}/">{{ ticket.queue.slug }}-{{ ticket.id }}</a>
    </li>
    <li class="breadcrumb-item active">{% trans "Edit Ticket" %}</li>
{% endblock %}

{% block helpdesk_body %}
    <div class="col-xs-6">
        <div class="panel panel-default">
            <div class="panel-body"><h2>{% trans "Edit a Ticket" %}</h2>
                <p>
                    {% trans "Unless otherwise stated, all fields are required." %}
                    {% trans "Please provide as descriptive a title and description as possible." %}
                </p>
                <p>
                    <strong>{% trans "Note" %}:</strong>
                    {% blocktrans %}Editing a ticket does <em>not</em> send an e-mail to the ticket owner or submitter. No new details should be entered, this form should only be used to fix incorrect details or clean up the submission.{% endblocktrans %}
                </p>
                {% if errors %}<p class="text-danger">{% for error in errors %}{% trans "Error: " %}{{ error }}<br>{% endfor %}</p>{% endif %}
                <form method='post' name="ticket_submission_form">
                    {% csrf_token %}
                    <fieldset>
                        {{ form|bootstrap4form }}
                        <div class='buttons form-group'>
                            <input type='submit' class="btn btn-primary btn" value='{% trans "Save Changes" %}'/>
                            <a href='{{ ticket.get_absolute_url }}'>
                                <button class="btn btn-danger">{% trans "Cancel Changes" %}</button>
                            </a>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>

    {% include 'helpdesk/include/edit_md_preview_script.html' %} 
{% endblock %}

{% block helpdesk_js %}
    {{ form.media.js }}
{% endblock %}

helpdesk/templates/helpdesk/kb_article_base.html
{% load i18n helpdesk_staff %}
{% block header %}

<div class="row mx-2">
    <div class="w-100 d-inline-flex">
        <h2>{% blocktrans with item.question as itemq %}{{ itemq }}{% endblocktrans %}</h2>
        <div class="flex-fill d-flex justify-content-end">
            {% if  user.is_authenticated and user|is_helpdesk_staff %}
            <a class="btn btn-warning align-self-center mr-2" href="{% url 'helpdesk:edit_kb_article' category.slug item.id %}{{ user_info.url }}">
                <i class="fa fa-pen mr-1"></i>Edit Article
            </a>
            <a class="btn btn-danger align-self-center" data-toggle="modal" data-target="#deleteModal">
                <i class="fa fa-trash mr-1"></i>Delete Article
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

<div class="container">
    <div class="row" style="margin-top:15px;display:block;">
        {{ item.get_markdown }}
    </div>
</div>
{% block footer %}
<div class="row mx-1 mb-2">
    <div class="card bg-light w-100">
        <div class="p-2">
            {% if kb_forms %}
            <a class="dropdown-toggle btn btn-success " href="#" id="ticketsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-fw fa-plus-circle"></i> {% trans category.form_submission_text %}
            </a>
            <div class="dropdown-menu" aria-labelledby="ticketsDropdown">
                {% for f in kb_forms %}
                <a class="dropdown-item small text-wrap" href="{% if iframe %}{% url 'helpdesk:submit_iframe' %}{% else %}{% url 'helpdesk:submit' f.id %}{%endif%}?{% if category.queue %}queue={{category.queue.pk}}&_readonly_fields_=queue&{%endif%}kbitem={{item.id}}{% if query_param_string %}&{{query_param_string}}{% endif %}">{{ f.name }}</a>
                {% endfor %}
            </div>
            {% endif %}
            {% if staff %}
            <a href="{% url 'helpdesk:list' %}?kb={{item.id}}" class="">
                <div class="btn btn-warning "><i class="fa fa-search fa-lg"></i> {{item.num_open_tickets}} {% trans 'open tickets' %}</div>
            </a>
            {% endif %}
            <a class="float-right btn btn-secondary {% if not next_item %} disabled{% endif %}" href="{{ next_item.get_absolute_url }}/{{ user_info.url }}">
                Next Item <i class="fa fa-angle-double-right"></i>
            </a>
            <a style="vertical-align:center" class="float-right mr-2 btn btn-secondary {% if not prev_item %} disabled{% endif %}" href="{{ prev_item.get_absolute_url }}/{{ user_info.url }}" role="button">
                <i class="fa fa-angle-double-left"></i> Previous Item
            </a>
        </div>
    </div>
</div>

{% endblock %}

{% url 'helpdesk:delete_kb_article' category.slug item.id as delete_url%}
{% include 'helpdesk/include/confirm_delete.html' with type="Article" title=item.title delete_url=delete_url %}

helpdesk/templates/helpdesk/navigation-sidebar.html
{% load i18n helpdesk_staff %}
{% load form_list %}
{% form_list user request as forms %}
{% load saved_queries %}
{% with user|saved_queries as user_saved_queries_ %}
{% with request.resolver_match.url_name as url_name %}
    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
    {% if helpdesk_settings.HELPDESK_NAVIGATION_ENABLED and user.is_authenticated or user|is_helpdesk_staff %}
        <li class="nav-item {% if url_name == 'dashboard' %}active{% endif %}">
          <a class="nav-link" href="{% url 'helpdesk:dashboard' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>{% trans "Helpdesk Dashboard" %}</span>
          </a>
        </li>
        <li class="nav-item {% if url_name == 'list' %}active{% endif %}">
          <a class="nav-link" href="{% url 'helpdesk:list' %}">
            <i class="fas fa-fw fa-tasks"></i>
            <span>{% trans "All Tickets" %}</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="queriesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-search"></i>
            <span>{% trans "Saved Searches" %}</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="queriesDropdown">
            {% if user_saved_queries_ %}
            {% for q in user_saved_queries_ %}
            {% if not q.shared %}
            <a class="dropdown-item text-wrap" href="{% url 'helpdesk:list' %}?saved-query={{ q.id }}">{{ q.title }}</a>
            {% endif %}
            {% endfor %}
            {% else %}
            <p class="dropdown-item text-wrap">{% trans "No saved searches currently available. You can create one in the All Tickets page." %}</p>
            {% endif %}
          </div>
        </li>
        <li class="nav-item dropdown {% if url_name == 'submit' %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="ticketsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-plus-circle"></i>
            <span>{% trans "New Ticket" %}</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="ticketsDropdown">
            {% if forms %}
            {% for f in forms %}
            <a class="dropdown-item text-wrap" href="{% url 'helpdesk:submit' f.id %}{{ user_info.url }}">{{ f.name }}</a>
            {% endfor %}
            {% else %}
            <p class="dropdown-item text-wrap">{% trans "No forms are available." %}</p>
            {% endif %}
          </div>
        </li>
        <li class="nav-item {% if url_name == 'report_index' %}active{% endif %}">
          <a class="nav-link" href="{% url 'helpdesk:report_index' %}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>{% trans "Reports" %}</span>
          </a>
        </li>
        {% if helpdesk_settings.HELPDESK_KB_ENABLED %}
        <li class="nav-item {% if 'kb_' in url_name %}active{% endif %}">
          <a class="nav-link" href="{% url 'helpdesk:kb_index' %}">
            <i class="fas fa-fw fa-database"></i>
            <span>{% trans "Knowledge<wbr>base" %}</span>
          </a>
        </li>
        {% endif %}
        {% if user_info.default_org.name == 'Building Performance Colorado' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'helpdesk:payment' %}">
            <i class="fas fa-money-check"></i>
            <span>{% trans "Payment Portal" %}</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="https://energyoffice.colorado.gov/accessibility"  target="_blank">
            <i class="fas fa-fw fa-universal-access"></i>
            <span>{% trans "Accessibility Notice" %}</span>
          </a>
        </li>
        {% endif %}

        <li class="dropdown-divider"></li>
        <li class="nav-item dropdown {% if url_name == 'user_settings' or url_name == 'system_settings' or 'rss_' in url_name %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-cog"></i>
              <span>Settings</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="userDropdown">
            <a class="dropdown-item text-wrap" href="{% url 'helpdesk:user_settings' %}"><i class="fas fa-fw fa-user-cog"></i> {% trans "User Settings" %}</a>
            <a class="dropdown-item text-wrap" href="{% url 'helpdesk:rss_index' %}"><i class="fas fa-fw fa-rss-square"></i> {% trans "RSS Feeds" %}</a>
            {% if helpdesk_settings.HELPDESK_SHOW_CHANGE_PASSWORD and user.has_usable_password %}
            <a class="dropdown-item text-wrap" href="{% url 'helpdesk:password_change' %}"><i class="fas fa-fw fa-user-secret"></i> {% trans "Change password" %}</a>
            {% endif %}
            <div class="dropdown-divider"></div>
            {% if user|is_helpdesk_staff %}
            <a class="dropdown-item text-wrap" href="{% url 'helpdesk:system_settings' %}"><i class="fas fa-fw fa-cogs"></i> {% trans "System Settings" %}</a>
            <div class="dropdown-divider"></div>
            {% endif %}
            <a class="dropdown-item text-wrap" href="{% url 'helpdesk:logout' %}?next=/helpdesk/{{ user_info.url }}"><i class="fas fa-fw fa-sign-out-alt"></i> {% trans "Logout" %}</a>
          </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'seed:home' %}">
                <i class="fas fa-city"></i>
                <span>BEAM</span>
            </a>
        </li>
    {% else %}
        {# Public menu #}
        <li class="nav-item {% if url_name == 'home' %}active{% endif %}">
          <a class="nav-link" href="{% url 'helpdesk:home' %}{{ user_info.url }}">
            <i class="fas fa-fw fa-home"></i>
            <span>{% trans "Homepage" %}</span>
          </a>
        </li>
        <li class="nav-item dropdown {% if url_name == 'submit' %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="ticketsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-plus-circle"></i>
            <span>{% trans "New Ticket" %}</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="ticketsDropdown">
            {% if forms %}
            {% for f in forms %}
            {% if f.organization__name == user_info.default_org.name %}
            <a class="dropdown-item text-wrap" href="{% url 'helpdesk:submit' f.id %}{{ user_info.url }}">{{ f.name }}</a>
            {% endif %}
            {% endfor %}
            {% else %}
            <p class="dropdown-item text-wrap">{% trans "No forms are available." %}</p>
            {% endif %}
          </div>
        </li>
        {% if helpdesk_settings.HELPDESK_KB_ENABLED %}
        <li class="nav-item {% if 'kb_' in url_name %}active{% endif %}">
          <a class="nav-link" href="{% url 'helpdesk:kb_index' %}{{ user_info.url }}">
            <i class="fas fa-fw fa-database"></i>
            <span>{% trans "Knowledge<wbr>base" %}</span>
          </a>
        </li>
        {% endif %}
        {% if user_info.default_org.name == 'Building Performance Colorado' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'helpdesk:payment' %}{{ user_info.url }}">
            <i class="fas fa-money-check"></i>
            <span>{% trans "Payment Portal" %}</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="https://energyoffice.colorado.gov/accessibility"  target="_blank">
            <i class="fas fa-fw fa-universal-access"></i>
            <span>{% trans "Accessibility Notice" %}</span>
          </a>
        </li>
        {% endif %}
        <li class="dropdown-divider"></li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'seed:home' %}#/properties">
                <i class="fas fa-city"></i>
                <span>BEAM {% trans "Inventory" %}</span>
            </a>
        </li>
    {% endif %}
    </ul>

{% endwith %}
{% endwith %}

helpdesk/templates/helpdesk/tag_list.html
{% extends "helpdesk/base.html" %}{% load i18n %}

{% block helpdesk_title %}{% trans "Tags" %}{% endblock %}

{% block helpdesk_breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'helpdesk:system_settings' %}">{% trans "System Settings" %}</a>
</li>
<li class="breadcrumb-item active">
    Tags
</li>
{% endblock %}

{% block helpdesk_body %}{% blocktrans %}
<h2>Tags</h2>

<p>Here you can create, edit, and delete Helpdesk tags. They can be used to sort and categorize tickets. Helpdesk will not automatically apply or remove tags from tickets.</p>{% endblocktrans %}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <i class="fas fa-table mr-1"></i>
                {% trans "Tag List" %}
                <div class="flex-fill d-flex justify-content-end">
                    <a class="float-right" href='add/'>
                        <button class="btn btn-primary">
                            <i class="fa fa-plus"></i> {% trans "Create" %}
                        </button>
                    </a>
                </div>
            </div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="thead-light">
                            <tr>
                                <th class="align-middle">{% trans "Tag" %}</th>
                                <th class="text-center align-middle" style="width:20%;">{% trans "View Tagged Tickets" %}</th>
                                <th class="text-center align-middle" style="width:1%;">{% trans "Edit" %}</th>
                                <th class="text-center align-middle" style="width:1%;">{% trans "Delete" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for tag in tag_list %}
                            <tr>
                                <td class="align-middle"><span style="font-size:95%;" class="badge badge-{{tag.color}}">{{ tag.name }}</span></td>
                                <td class="text-center align-middle"><a href="{% url 'helpdesk:list' %}?t={{ tag.id }}">View tickets</a></td>
                                <td class="text-center align-middle"><a href='{% url 'helpdesk:tag_edit' tag.id %}'><button class="btn btn-warning btn-xs"><i class="fa fa-pen"></i></button></a></td>
                                <td class="text-center align-middle"><a href='{% url 'helpdesk:tag_delete' tag.id %}'><button class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

{% endblock %}