helpdesk/urls.py
"""
django-helpdesk - A Django powered ticket tracker for small enterprise.

(c) Copyright 2008 Jutda. All Rights Reserved. See LICENSE for details.

urls.py - Mapping of URL's to our various views. Note we always used NAMED
          views for simplicity in linking later on.
"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from helpdesk.decorators import helpdesk_staff_member_required, protect_view
from helpdesk import settings as helpdesk_settings
from helpdesk.views import feeds, staff, public, kb, login
try:
    # TODO: why is it imported? due to some side-effect or by mistake?
    import helpdesk.tasks  # NOQA
except ImportError:
    pass


class DirectTemplateView(TemplateView):
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        if self.extra_context is not None:
            for key, value in self.extra_context.items():
                if callable(value):
                    context[key] = value()
                else:
                    context[key] = value
        return context


app_name = 'helpdesk'

base64_pattern = r'(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'

urlpatterns = [
    url(r'^dashboard/$',
        staff.dashboard,
        name='dashboard'),

    url(r'^tickets/$',
        staff.ticket_list,
        name='list'),

    url(r'^tickets/tags/$',
        staff.get_tags,
        name='get_tags'),

    url(r'^tickets/update/$',
        staff.mass_update,
        name='mass_update'),

    url(r'^tickets/update_tags/$',
        staff.mass_update_tags,
        name='mass_update_tags'),
    
    url(r'^tickets/get_elapsed_time/(?P<ticket_id>[0-9]+)/$',
        staff.get_elapsed_time,
        name='get_elapsed_time'),

    
    url(r'^tickets/start_timer/$',
        staff.start_timer,
        name='start_timer'),
    
    url(r'^tickets/stop_timer/$',
        staff.stop_timer,
        name='stop_timer'),


    url(r'^tickets/merge$',
        staff.merge_tickets,
        name='merge_tickets'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/$',
        staff.view_ticket,
        name='view'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/followup_edit/(?P<followup_id>[0-9]+)/$',
        staff.followup_edit,
        name='followup_edit'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/followup_delete/(?P<followup_id>[0-9]+)/$',
        staff.followup_delete,
        name='followup_delete'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/edit/$',
        staff.edit_ticket,
        name='edit'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/update/$',
        staff.update_ticket,
        name='update'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/delete/$',
        staff.delete_ticket,
        name='delete'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/hold/$',
        staff.hold_ticket,
        name='hold'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/unhold/$',
        staff.unhold_ticket,
        name='unhold'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/$',
        staff.ticket_cc,
        name='ticket_cc'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/add/$',
        staff.ticket_cc_add,
        name='ticket_cc_add'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/delete/(?P<cc_id>[0-9]+)/$',
        staff.ticket_cc_del,
        name='ticket_cc_del'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/dependency/add/$',
        staff.ticket_dependency_add,
        name='ticket_dependency_add'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/dependency/delete/(?P<dependency_id>[0-9]+)/$',
        staff.ticket_dependency_del,
        name='ticket_dependency_del'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/attachment_delete/(?P<attachment_id>[0-9]+)/$',
        staff.attachment_del,
        name='attachment_del'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/beam_unpair/(?P<inventory_type>(property|taxlot))/(?P<inventory_id>[0-9]+)/$',
        staff.beam_unpair,
        name='ticket_beam_unpair'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/edit_tags/$', staff.edit_ticket_tags, name='edit_ticket_tags'),

    url(r'^raw/(?P<type>\w+)/$',
        staff.raw_details,
        name='raw'),

    url(r'^rss/$',
        staff.rss_list,
        name='rss_index'),

    url(r'^reports/$',
        staff.report_index,
        name='report_index'),

    url(r'^reports/(?P<report>\w+)/$',
        staff.run_report,
        name='run_report'),

    url(r'^save_query/$',
        staff.save_query,
        name='savequery'),

    url(r'^delete_query/(?P<id>[0-9]+)/$',
        staff.delete_saved_query,
        name='delete_query'),

    url(r'^reject_query/(?P<id>[0-9]+)/$',
        staff.reject_saved_query,
        name='reject_query'),

    url(r'^reshare_query/(?P<id>[0-9]+)/$',
        staff.reshare_saved_query,
        name='reshare_query'),

    url(r'^unshare_query/(?P<id>[0-9]+)/$',
        staff.unshare_saved_query,
        name='unshare_query'),

    url(r'^settings/$',
        staff.EditUserSettingsView.as_view(),
        name='user_settings'),

    url(r'^ignore/$', staff.email_ignore, name='email_ignore'),
    url(r'^ignore/add/$', staff.email_ignore_add, name='email_ignore_add'),
    url(r'^ignore/edit/(?P<id>[0-9]+)/$', staff.email_ignore_edit, name='email_ignore_edit'),
    url(r'^ignore/delete/(?P<id>[0-9]+)/$', staff.email_ignore_del, name='email_ignore_del'),

    url(r'^tag/$', staff.tag_list, name='tag_list'),
    url(r'^tag/add/$', staff.tag_add, name='tag_add'),
    url(r'^tag/edit/(?P<id>[0-9]+)/$', staff.tag_edit, name='tag_edit'),
    url(r'^tag/delete/(?P<id>[0-9]+)/$', staff.tag_delete, name='tag_delete'),

    url(r'^preset_reply/$', staff.preset_reply_list, name='preset_reply_list'),
    url(r'^preset_reply/add/$', staff.preset_reply_add, name='preset_reply_add'),
    url(r'^preset_reply/edit/(?P<id>[0-9]+)/$', staff.preset_reply_edit, name='preset_reply_edit'),
    url(r'^preset_reply/delete/(?P<id>[0-9]+)/$', staff.preset_reply_delete, name='preset_reply_delete'),

    url(r'^email_template/$', staff.email_template_list, name='email_template_list'),
    url(r'^email_template/edit/(?P<id>[0-9]+)/$', staff.email_template_edit, name='email_template_edit'),
    url(r'^email_template/default/(?P<id>[0-9]+)/$', staff.email_template_default, name='email_template_default'),

    url(r'^payment/settings/$', staff.payment_settings,  name='payment_settings'),

    url(r'^preview_html$', staff.preview_html, name="preview_html"),

    url(r'^timeline_ticket_list/(?P<query>{})$'.format(base64_pattern),
        staff.timeline_ticket_list,
        name="timeline_ticket_list"),

    url(r'set_default_org/(?P<user_id>[0-9]+)/(?P<org_id>[0-9]+)/$',
        staff.set_default_org,
        name="set_default_org"),

    url(r'set_user_timezone/$',
        staff.set_user_timezone,
        name="set_user_timezone"),

    url(r'emails/(?P<ticket_id>[0-9]+)/$',
        staff.enable_disable_emails,
        name="enable_disable_emails"),

    url(r'pair_property_milestone/(?P<ticket_id>[0-9]+)/$',
        staff.pair_property_milestone,
        name="pair_property_milestone"),

    url(r'pair_property_ticket/(?P<ticket_id>[0-9]+)/$',
        staff.pair_property_ticket,
        name="pair_property_ticket"),

    url(r'copy_to_beam/(?P<ticket_id>[0-9]+)/$',
        staff.load_copy_to_beam,
        name="copy_to_beam"),

    url(r'get_building_data/(?P<ticket_id>[0-9]+)/$',
        staff.get_building_data,
        name="get_building_data"),

    url(r'update_building_data/(?P<ticket_id>[0-9]+)/$',
        staff.update_building_data,
        name="update_building_data"),

    url(r'edit_inventory_labels/(?P<inventory_type>(property|taxlot))/(?P<ticket_id>[0-9]+)/$',
        staff.edit_inventory_labels,
        name="edit_inventory_labels"),

    url(r'export_report/$',
        staff.export_report,
        name="export_report"),
]

urlpatterns += [
    # 9/24: Removed form and 'View Ticket' feature from homepage -- so just display the KB home. Add this back later
    # url(r'^$',
    #    protect_view(public.Homepage.as_view()),
    #    name='home'),

    url(r'^tickets/submit/(?P<form_id>[0-9]+)/$',
        public.create_ticket,
        name='submit'),

    url(r'^tickets/submit_iframe/$',
        public.CreateTicketIframeView.as_view(),
        name='submit_iframe'),

    url(r'^tickets/success_iframe/$',  # Ticket was submitted successfully
        public.SuccessIframeView.as_view(),
        name='success_iframe'),

    url(r'^view/$',
        public.view_ticket,
        name='public_view'),

    url(r'^evaluate_derived_column/$',
        public.evaluate_derived_column,
        name='evaluate_derived_column'),

    url(r'^change_language/$',
        public.change_language,
        name='public_change_language'),
    
    url(r'^bps_pathway_calculator/$',
        public.bps_pathway_calculator,
        name='public_bps_pathway_calculator'),

    url(r'^payment/$',
        public.BuildingOrderView.as_view(),
        name='payment'),

    url(r'^payment/property/$',
        public.lookup_building_for_payment,
        name='lookup_building_for_payment'),

    url(r'^payment/complete/$', public.payment_complete, name='payment_complete'),
    url(r'^payment/canceled/$', public.payment_failed, name='payment_canceled'),
    url(r'^payment/failed/$', public.payment_failed, name='payment_failed'),
    url(r'^payment/duplicate/$', public.payment_failed, name='payment_duplicate'),
]

urlpatterns += [
    url(r'^rss/user/(?P<user_name>[^/]+)/$',
        helpdesk_staff_member_required(feeds.OpenTicketsByUser()),
        name='rss_user'),

    url(r'^rss/user/(?P<user_name>[^/]+)/(?P<queue_slug>[A-Za-z0-9_-]+)/$',
        helpdesk_staff_member_required(feeds.OpenTicketsByUser()),
        name='rss_user_queue'),

    url(r'^rss/queue/(?P<queue_slug>[A-Za-z0-9_-]+)/$',

helpdesk/templates/helpdesk/include/attachment_input.html
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <button id="{{ widget.name}}_upload" type="button" class="btn btn-secondary" onclick="document.getElementById('id_{{ widget.name }}').click()">Upload</button>
    </div>
    <input type="file" hidden onchange="uploadFile('{{widget.name}}');" id="id_{{ widget.name}}" name="{{ widget.name }}" {% include "django/forms/widgets/attrs.html" %}>
    <input type="text" class="form-control" disabled id="{{widget.name}}_text" value="{{ widget.value }}">
    <div class="input-group-append" id="{{ widget.name }}_interact" {% if not widget.value %}hidden{% endif %}>
        <button class="btn btn-outline-secondary" id="{{ widget.name }}_copylink" type="button" onclick="navigator.clipboard.writeText({% if not val|slice:':4' in 'http' and widget.attrs.url|first in '/' %}window.location.origin + {% endif %}'{{ widget.attrs.url }}')">Copy Link</button>
        <a class="btn btn-outline-secondary" id="{{ widget.name }}_preview" type="button" href="{{ widget.attrs.url }}" rel="noopener noreferrer" target="_blank"
            title="Preview attachment in new tab">Preview</a>
    </div>
</div>

helpdesk/templates/helpdesk/include/attachment_input_script.html
<script type='text/javascript' language='javascript'>
    function uploadFile(widgetName) {
        src_input = document.getElementById('id_' + widgetName);
        data = new FormData();
        data.append('file', src_input.files[0]);
        {% if item.id %} data.append('kbitem_id', {{ item.id }}); {% endif %}
        data.append('id', document.querySelector('#id_' + widgetName.replace('-file','-id')).value);
        data.append('csrfmiddlewaretoken', document.querySelector('input[name=csrfmiddlewaretoken]').value);
        
        $.ajax({
            data: data,
            url: "{%url 'helpdesk:upload_attachment' %}",
            type: 'POST',
            processData: false,
            contentType: false,
    
            success: function(response) {
                $('#' + widgetName + '_upload').popover('dispose');
                if (response['uploaded']) {
                    document.getElementById(widgetName + '_text').value = src_input.files[0].name;
                    document.querySelector('#id_' + widgetName.replace('-file','-id')).value = response['id'];
                    document.getElementById(widgetName + '_interact').hidden = false;
                    document.getElementById(widgetName + '_preview').href = response['url'];
                    if (!response['url'].startsWith('http') && response['url'].startsWith('/')) {
                        response['url'] = window.location.origin + response['url'];
                    }
                    document.getElementById(widgetName + '_copylink').onclick = () => {navigator.clipboard.writeText(response['url'])};
                } else {
                    console.log("failed");
                    // Format errors
                    content = '<span class="mb-2">Fix the following errors in order to copy this field to another form</span><ul class="list-group">';
                    // for (const [field, error] of Object.entries(response['errors'])) {
                    //     content += `
                    //         <li class="list-group-item">
                    //             <span class="text-danger font-weight-bold">${field}</span>
                    //             <br>
                    //             ${error}    
                    //         </li>
                    //     `;
                    // }
                    content += '</ul>';
    
                    // Trigger error popover
                    $('#' + widgetName + '_upload').popover({
                        title: 'Field Errors',
                        content: 'Failed',
                        html: true,
                        placement: 'top',
                        trigger: 'focus'
                    });
                    $('#' + widgetName + '_upload').popover('show');
                }
            },
        });
    }
</script>

helpdesk/templates/helpdesk/include/bulk_replies.html
{% load i18n humanize %}

<div class="modal fade" id="bulkRepliesModal" tabindex="-1" role="dialog" aria-labelledby="bulkRepliesModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="bulkRepliesModalLabel">Bulk Replies</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <fieldset>
                    <dl>
                        {% if preset_replies %}
                        <dd><label for='id_preset'><b>{% trans "Select a Preset Reply" %}</b></label>
                        <select name='preset' id='id_preset' class='form-control'><option value=''>------</option>{% for preset in preset_replies %}<option value='{{ preset.id }}'>{{ preset.name }}</option>{% endfor %}</select><br/>
                        </dd>
                        {% endif %}
                        <dd><label for='id_public'><input type='checkbox' id='id_public' name='public' />&nbsp; <b>{% trans 'Make this update public?' %}</b></dd>
                        <dd class='form_help_text'>{% trans "If public, an email will be sent to the submitter, primary contact, copied nonusers, and any other email addresses listed on the form.<br>If private, an email will only be sent to the assigned staff owner and internal users. Use this to leave internal comments, questions, and flags. Responses will <i>not</i> be sent to the original sender. " %}</dd>
                    </dl>
                </fieldset>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button"  class="btn btn-danger" onclick="onBulkRepliesConfirm()">Confirm</button>
            </div>
        </div>
    </div>
</div>

helpdesk/templates/helpdesk/include/clearable_file_input.html
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <button id="{{ widget.name}}_upload" type="button" class="btn btn-secondary">{% trans "Upload" %}</button>
    </div>
    <input type="text" class="form-control" disabled id="{{widget.name}}_text" value="{{widget.value}}">
    <div class="input-group-append" id="{{ widget.name }}_interact" style="display:none;">
        <button id="{{widget.name}}_delete" type="button" class="btn btn-danger">{% trans "Remove" %}</button>
    </div>
</div>
<div><input type="file" hidden id="id_{{ widget.name}}" name="{{ widget.name }}" {% include "django/forms/widgets/attrs.html" %}></div>
<script>
    $('#{{widget.name}}_upload').on('click', function() {
        $('#id_{{ widget.name }}').click()
    });

    $('#id_{{widget.name}}').on('change', function() {
        src_input = document.getElementById('id_{{widget.name}}');
        $('#{{ widget.name }}_text').val(src_input.files[0].name);
        $('#{{ widget.name }}_interact').toggle();
    });

    $('#{{widget.name}}_delete').on('click', function() {
        $('#id_{{widget.name}}').val('');
        $('#{{widget.name}}_text').val('None');
        $('#{{ widget.name }}_interact').toggle();
    });
</script>

helpdesk/templates/helpdesk/include/comment_md_preview.html
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" data-bs-tabs="tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#comment_edit">Edit</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#comment_preview" onclick="updatePreview_comment()">Preview</a>
            </li>
        </ul>
    </div>
    <div class="card-body tab-content" style='overflow-y: auto'>
        <div id="comment_edit" class="tab-pane active">
            <textarea class="form-control" name="comment" id="commentBox" cols="40" rows="10" spellcheck="true" data-ms-editor="true"></textarea>
        </div>
        <div id="comment_preview" class="tab-pane">
            <div id="comment_md_preview"></div>
        </div>
    </div>
</div>

<script type='text/javascript' language='javascript'>
    function updatePreview_comment() {
        $.ajax({
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                md: $('#commentBox').val()
            },
            url: "{% url 'helpdesk:preview_markdown'  %}",
            type: 'POST',
            success: function(response) {
                $('#comment_md_preview').html(response['md_html'])
            },
        });
    }
</script>

helpdesk/templates/helpdesk/include/derived_column_widget.html
<div class="input-group mb-3">
    <input type="text" disabled id="{{widget.name}}_text" value="{{widget.value}}" {% include "django/forms/widgets/attrs.html" %}>
    <div class="input-group-append" id="{{ widget.name }}_interact">
        <button id="{{widget.name}}_evaluate" type="button" class="btn btn-primary">Evaluate</button>
    </div>
</div>
<script>
  function evaluate() {
    $('#{{widget.name}}_text').val('Loading...')

    const data = new FormData(document.forms['ticket_submission_form'])
    data.append('form_id', $('#{{widget.name}}_text').attr('data-form-id'))
    data.append('derived_column_field', '{{widget.name}}')
    data.append('building_id', document.getElementById('id_building_id')?.value)

    $.ajax({
      url: "{% url 'helpdesk:evaluate_derived_column' %}",
      type: 'POST',
      processData: false,
      contentType: false,
      data: data,
      success: function (response) {
        $('#{{widget.name}}_text').val(response.data)
      }
    })
  }

  $('#{{widget.name}}_evaluate').on('click', evaluate);
  evaluate()
</script>

helpdesk/templates/helpdesk/include/edit_md_preview.html
{% load i18n humanize %}

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" data-bs-tabs="tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#{{widget.name}}_edit">{% trans "Edit" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#{{widget.name}}_preview" onclick="updatePreview('{{widget.name}}')">{% trans "Preview" %}</a>
            </li>
        </ul>
    </div>
    <div class="card-body tab-content" style='overflow-y: auto'>
        <div id="{{widget.name}}_edit" class="tab-pane active">
            <textarea class="form-control" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% spaceless %}
                {% if widget.value %}{{ widget.value }}{% endif %}
            {% endspaceless %}</textarea>
        </div>
        <div id="{{widget.name}}_preview" class="tab-pane" style='max-height: 75vh;'>
            <div id="{{widget.name}}_md_preview"></div>
        </div>
    </div>
</div>

helpdesk/templates/helpdesk/include/edit_md_preview_script.html
<script type='text/javascript' language='javascript'>
    function updatePreview(widget_name) {
        is_kbitem = document.getElementById('id_answer') != null
        $.ajax({
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                md: $('#id_' + widget_name).val(),
                is_kbitem: is_kbitem
            },
            url: "{% url 'helpdesk:preview_markdown' %}",
            type: 'POST',
            success: function(response) {
                $('#' + widget_name + '_md_preview').html(response['md_html'])
            },
        });
    }
</script>

helpdesk/templates/helpdesk/include/multi_text_input.html
<div id="id_{{widget.name}}" class="card">
    {% comment %} <input type="hidden" id="id_agg_{{widget.name}}" name="agg_{{widget.name}}" value="[]"> {% endcomment %}
    <div id="{{widget.name}}_strings" class="card-body">
        {% for subwidget in widget.subwidgets %}
        <div class="mb-2">
            {% include "django/forms/widgets/input.html" with widget=subwidget %}
        </div>
        {% endfor %}
    </div>
    <div class="card-footer">
        <a><button id="{{ widget.name }}_add_string" type="button" class="btn btn-primary float-right"><i class="fa fa-plus mr-1"></i>Add</button></a>
    </div>
</div>


<script type='text/javascript' language='javascript'>
    $("#{{ widget.name }}_add_string").on('click', function() {
        // Create new input element and append it to the input container
        new_input_num = document.getElementById("{{widget.name}}_strings").children.length
        new_elem_type = document.getElementById("{{widget.name}}_strings").children[0].children[0].type
        new_elem = document.createElement('div')
        new_elem.setAttribute('class', 'mb-2')
        new_elem.innerHTML = '<input type="' + new_elem_type + '" name="{{ widget.name }}_0" class=" form-control" id="id_{{ widget.name }}_0" spellcheck="false" data-ms-editor="true">'.replaceAll("{{ widget.name }}_0", "{{ widget.name }}_" + new_input_num);
        document.getElementById('{{ widget.name }}_strings').appendChild(new_elem);
    });
</script>

helpdesk/templates/helpdesk/include/prepopulate_form_input.html
<div class="input-group mb-3">
    <input type="text" name="{{ widget.name }}" class="form-control" id="id_{{widget.name}}" value="{{widget.value}}">
    <div class="input-group-append" id="{{ widget.name }}_interact">
        <button id="{{widget.name}}_prepopulate" type="button" class="btn btn-primary">Prepopulate</button>
    </div>
</div>
<script>
    $('#{{widget.name}}_prepopulate').on('click', function() {
        window.location = window.location.origin + window.location.pathname + '?e_building_id=' + $('#id_{{widget.name}}').val()
    });
</script>

helpdesk/templates/helpdesk/include/searchable_select.html
<div hidden>
    {% include 'django/forms/widgets/select.html' %}
</div>
<div class="input-group mb-2">
    <div class="input-group-prepend">
        <button type="button" id='new_{{widget.name}}' class="btn btn-outline-secondary" data-toggle="collapse" data-target="#collapse_list_{{widget.name}}">Select New</button>
    </div>
    <input type="text" id="colselection_{{ widget.name }}" placeholder="None" class="form-control" readOnly 
        value="{% for group_name, group_choices, group_index in widget.optgroups %}{% for option in group_choices %}{% if option.value|stringformat:'s' == widget.value.0 %}{{ option.label }}{% endif %}{% endfor %}{% endfor %}">
</div>
<div class="collapse" id="collapse_list_{{ widget.name }}">
    <div class="card pt-0 mx-0 my-0 rounded-lg overflow-hidden" style="max-height: 25vh;">
        <div class="card-header">
            <input id="colsearch_{{ widget.name }}" onkeydown="if (event.keyCode == 13) {event.preventDefault()}" oninput="debounced('{{ widget.name }}')" type="search" class="form-control" autocomplete="false" placeholder="Type to filter..." 
            spellcheck="false" data-ms-editor="true" {% include "django/forms/widgets/attrs.html" %}>
        </div>
        <div class="card-body p-2 overflow-auto">
            <ul id="collist_{{widget.name}}" class="list-unstyled mb-0 overflow-auto">
                {% for group_name, group_choices, group_index in widget.optgroups %}{% for option in group_choices %}
                <li>
                    <a class="dropdown-item rounded-lg" onclick="selectOption(this, '{{ widget.name }}')" data-value="{{ option.value|stringformat:'s' }}">
                        {{option.label}}
                    </a>                
                </li>
                {% endfor %}{% endfor %}
            </ul>
        </div>
    </div>
</div>

helpdesk/templates/helpdesk/include/searchable_select_script.html
<script type='text/javascript' language='javascript'>
    function filterColumns(widgetName) {
        if (document.getElementById('colsearch_' + widgetName) == null) {
            return
        }
        query = document.getElementById('colsearch_' + widgetName).value.trim().toLowerCase()
        for (const entry of document.getElementById('collist_' + widgetName).children) {
            if (!entry.children[0].innerText.toLowerCase().includes(query)) {
                entry.hidden = true
            } else {
                entry.hidden = false
            }
        }
    }

    function selectOption(src, widgetName) {
        document.getElementById('colselection_' + widgetName).value = src.innerText
        document.getElementById('id_' + widgetName).value = src.dataset.value
        document.getElementById('new_' + widgetName).click()
    }

    var debounced = debounce(filterColumns, 500)

    function debounce(func, wait, immediate) {
        var timeout;
        return function() {
            var context = this, args = arguments;
            var later = function() {
                timeout = null;
                if (!immediate) func.apply(context, args);
            };
            var callNow = immediate && !timeout;
            clearTimeout(timeout);
            timeout = setTimeout(later, wait);
            if (callNow) func.apply(context, args);
        };
    };
</script>